added generator in metadata
dlr-eoc/ukis-pysat pull request #133
Opened 2021-04-06 09:15 UTC by shiwakotisurendra

closes #127

2021-04-06 09:34 UTC, fwfichtner requested changes
Looks good, that's what we had in mind. Just some minor adaptions and then the tests.

2021-04-06 09:34 UTC, fwfichtner commented on ukis_pysat/data.py
> +        :generates: Metadata catalog of products that match query criteria (PySTAC Catalog).
it just generates the item now, right?

2021-04-06 09:34 UTC, fwfichtner commented on ukis_pysat/data.py
> +        # return catalog
better delete it right away please

2021-04-06 09:34 UTC, fwfichtner commented on ukis_pysat/data.py
> +        :generates: Metadata of product that matches srcid (PySTAC Catalog).
it is also just the item here

2021-04-06 12:44 UTC, fwfichtner approved these changes
well done, @MWieland is this good for you as well?

2021-04-06 13:06 UTC, fwfichtner commented on CHANGELOG.rst
> +- ``data``: generator added to query_metadata and query_metadata_srcid #127
```suggestion
- ``data``: generator instead of catalog return for query_metadata and query_metadata_srcid #127
```

2021-04-06 13:06 UTC, fwfichtner approved these changes

2021-04-07 14:19 UTC, MWieland approved these changes
Looks good to me. Well done.

2021-04-07 14:22 UTC, merged